Repository codeit-sprint14-part3-4/Taskify, pull requests merged in 2025-04, with the labels that each got.

#1 [Feature/tag] 색상 랜덤 구현하기
  src/components/common/tag/Tag.tsx
  src/components/common/tag/tag.module.css
  src/pages/testpage.tsx
Labels: 🎨스타일 (Style)

#2 ✨[Feature] Swagger 기반 API 모듈 전면 구현
  src/api/services/Invitations.tsx
  src/api/services/authServices.ts
  src/api/services/cards.tsx
  src/api/services/cardsServices.ts
  src/api/services/columns.tsx
  src/api/services/columnsServices.ts
  src/api/services/comments.tsx
  src/api/services/commentsServices.ts
  src/api/services/dashboards.tsx
  src/api/services/dashboardsServices.ts
  src/api/services/invitationsServices.ts
  src/api/services/members.tsx
  src/api/services/membersServices.ts
  src/api/services/users.tsx
  src/api/services/usersServices.ts
  src/pages/_app.tsx
  src/types/api/auth.ts
  src/types/api/cards.ts
  src/types/api/columns.ts
  src/types/api/comments.ts
  src/types/api/dashboards.ts
  src/types/api/invitations.ts
  src/types/api/menmbers.ts
  src/types/api/users.ts
  src/types/common/error.ts
  src/utils/handleError.ts
Labels: ✨기능 추가 (Feature), 📐아키텍처 (Structure)

#4 [Feature/sidebar] 반응형 사이드바 구현
  public/assets/icon/logo-icon.svg
  public/assets/icon/logo-title.svg
  public/assets/image/add-box.svg
  src/.gitattributes
  src/components/layout/sidebar/Sidebar.tsx
  src/components/layout/sidebar/sidebar.module.css
  src/pages/sidebarpage.tsx
  src/pages/testpage.tsx
Labels: ✨기능 추가 (Feature)

#8 [Feature/button] 공통 컴포넌트 - button(로그인, 수락/거절, 취소/확인, 삭제/입력) 추가
  .vscode/settings.json
  package-lock.json
  package.json
  postcss.config.mjs
  public/assets/icon/add_box.svg
  public/assets/icon/favicon.ico
  public/assets/image/logo_taskify.svg
  public/assets/image/text_taskify.svg
  src/components/common/button/Button.tsx
  src/components/common/button/ButtonDashboard.module.css
  src/components/common/button/ButtonDashboard.tsx
  src/components/common/button/button.module.css
  src/components/layout/gnb/Gnb.tsx
  src/components/layout/gnb/gnb.module.css
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/testpage.tsx
  src/styles/globals.css
  tailwind.config.js
  tsconfig.json
Labels: ✨기능 추가 (Feature), 🧼리팩토링 (Refactor)

#5 [Feature/input] 공통 컴포넌트 - input의 error 타입 focus 상태 등등 스타일 부분 적용
  package-lock.json
  package.json
  postcss.config.js
  public/assets/icon/homepage-logo-icon.svg
  public/assets/image/desktop.svg
  public/assets/image/homepagepeople.svg
  src/components/common/input.module.css
  src/components/common/input.tsx
  src/pages/index.module.css
  src/pages/index.tsx
  src/types/common/input.ts
Labels: ✨기능 추가 (Feature), 🐛버그 수정 (Bug)

#14 [Feature/mydashboard] mydashboard UI 구현
  public/assets/icon/email.svg
  src/components/common/button/button.module.css
  src/pages/mydashboard.tsx
  src/pages/mydashboard/mydashboard.module.css
  src/pages/mydashboard/mydashboard.tsx
  src/pages/testpage.tsx
  src/styles/globals.css
Labels: ✨기능 추가 (Feature)

#10 [Feature/navbar] 메인 네브바 - 전체적인 위치 틀만
  src/components/common/button/ButtonDashboard.module.css
  src/components/common/button/ButtonDashboard.tsx
  src/components/layout/gnb/HomeNavBar.tsx
  src/components/layout/gnb/homenavbar.module.css
  src/components/layout/sidebar/sidebar.module.css
  src/pages/testpage.module.css
  src/pages/testpage.tsx
Labels: ✨기능 추가 (Feature), 🧼리팩토링 (Refactor)

#9 [Feature/ mypage] UI 초기 구현
  package-lock.json
  public/assets/image/arrow-left.svg
  src/components/layout/sidebar/sidebar.module.css
  src/pages/mypage.module.css
  src/pages/mypage.tsx
  src/pages/testpage.tsx
  src/styles/globals.css
  src/styles/reset.css
Labels: ✨기능 추가 (Feature), 🎨스타일 (Style)

#16 [Feature/loginsignup] 로그인 회원가입 틀 + 토큰
  package-lock.json
  package.json
  public/assets/icon/check.svg
  public/assets/icon/hide_icon.svg
  public/assets/icon/open_hide.svg
  src/components/common/button/Button.tsx
  src/components/common/button/ButtonDashboard.module.css
  src/components/common/button/button.module.css
  src/components/common/input.tsx
  src/components/layout/gnb/gnb.module.css
  src/pages/login.tsx
  src/pages/login/index.tsx
  src/pages/login/login.module.css
  src/pages/signup.tsx
  src/pages/signup/index.tsx
  src/pages/signup/signup.module.css
  src/pages/testpage.tsx
  src/stores/auth.ts
  src/types/common/input.ts
  src/utils/axios.ts
Labels: ✨기능 추가 (Feature), 🐛버그 수정 (Bug)

#12 [Feature/dashboard-ui] dashboard 관련 컴포넌트 구현 및 dashboard UI 구현
  package-lock.json
  public/assets/icon/calendar.svg
  src/components/domain/dashboard/Card.tsx
  src/components/domain/dashboard/CardTable.tsx
  src/components/domain/dashboard/Column.tsx
  src/pages/dashboard/[id]/dashboard.module.css
  src/pages/dashboard/[id]/index.tsx
  src/styles/globals.css
Labels: ✨기능 추가 (Feature)

#15 [Fix/ mypage] 위치 조정 및 navbar 추가
  src/components/layout/sidebar/sidebar.module.css
  src/pages/mypage.module.css
  src/pages/mypage.tsx
Labels: ✨기능 추가 (Feature), 🎨스타일 (Style)

#18 [Feature/layout] homenavbar와 sidebar, 본문 배경색을 포함한 Layout 컴포넌트 구현
  package-lock.json
  src/components/layout/layout.tsx
  src/pages/dashboard/[id]/dashboard.module.css
  src/pages/dashboard/[id]/index.tsx
Labels: ✨기능 추가 (Feature), 🧼리팩토링 (Refactor)

#22 [Refactor] dashbaord UI 디자인적인 측면 일부 수정
  src/components/domain/dashboard/Card.tsx
  src/components/domain/dashboard/CardTable.tsx
  src/components/domain/dashboard/Column.tsx
Labels: 🧼리팩토링 (Refactor)

#25 [Feature/mydashboard-modal-api] mydashboard 모달 API 기능 구현 및 버튼 공통 컴포넌트명 수정
  src/components/common/commonbutton/CommonButton.tsx
  src/components/domain/modals/dashboardCreateModal/DashboardCreateModal.tsx
Labels: ✨기능 추가 (Feature), 🧼리팩토링 (Refactor)

#17 [Feature/landingpage] Landingpage 전체적인 디자인 완수 - Landingpage에서 사용할 Footerbar 컴포넌트와 FeatureCard 컴포넌트를 만들고 사용
  package-lock.json
  package.json
  public/assets/icon/envelope-email-icon.svg
  public/assets/icon/facebook-icon.svg
  public/assets/icon/instagram-logo-icon.svg
  public/assets/image/landing1.svg
  public/assets/image/landing2.svg
  public/assets/image/landing3.svg
  public/assets/image/landing4.svg
  public/assets/image/landing5.svg
  src/components/common/animatedSection/AnimatedSection.tsx
  src/components/common/input.module.css
  src/components/common/input.tsx
  src/components/featurecard/FeatureCard.tsx
  src/components/featurecard/featureCard.module.css
  src/components/layout/footerbar/Footerbar.tsx
  src/components/layout/footerbar/footerbar.module.css
  src/pages/index.module.css
  src/pages/index.tsx
  src/pages/test.tsx
  src/styles/globals.css
  src/types/common/featurecard.ts
Labels: ✨기능 추가 (Feature)

#23 [Feature/task-card-create-modal-ui] 할 일 생성 모달 UI 구현
  package-lock.json
  package.json
  public/assets/icon/add.svg
  src/components/domain/modals/Calendar.tsx
  src/components/domain/modals/TaskCardCreateModal.tsx
  src/components/domain/modals/custom-datepicker.module.css
  src/pages/test-task-card-create.tsx
  src/styles/globals.css
Labels: ✨기능 추가 (Feature), 🧼리팩토링 (Refactor)

#28 [Feature/mypage] 비밀번호 변경 및 프로필 수정 API 연동
  src/components/common/commonbutton/CommonButton.tsx
  src/components/common/dropdown/Dropdown.tsx
  src/components/domain/modals/FormModal.tsx
  src/components/domain/modals/Modal.tsx
  src/components/domain/modals/ModalButton.tsx
  src/components/domain/modals/basemodal.module.css
  src/components/domain/modals/formmodal.module.css
  src/components/domain/modals/modal.module.css
  src/pages/modaltest.tsx
  src/pages/mypage.module.css
  src/pages/mypage.tsx
  src/pages/sidebarpage.tsx
  src/types/api/users.ts
Labels: ✨기능 추가 (Feature)

#30 [Feature/tag-x-button] 태그 x 버튼 삭제 기능 추가
  src/components/common/tag/Tag.tsx
  src/components/domain/modals/TaskCardEditModal.tsx
Labels: ✨기능 추가 (Feature)

#32 [fix:task-card-modal] 드롭다운 담당자와 상태 추가
  src/components/domain/modals/TaskCardCreateModal.tsx
  src/components/domain/modals/TaskCardEditModal.tsx
  src/components/dropdown/StatusDropdown.tsx
  src/components/dropdown/UserDropdown.tsx
  src/types/common/tag.ts
Labels: ✨기능 추가 (Feature)

#36 [hotfix/loginrefactor] develop 이상한 부분 수정
  src/pages/login/index.tsx
  src/pages/mypage.tsx
  src/pages/signup/index.tsx
Labels: 🐛버그 수정 (Bug), 🔥긴급 수정 (Hotfix), 🧼리팩토링 (Refactor)

#35 [Feature/Sidebar]: 사이드바의 대시보드 생성 모달 연동 및 module.css 스타일 변경
  src/components/layout/sidebar/Sidebar.tsx
  src/components/layout/sidebar/sidebar.module.css
Labels: ✨기능 추가 (Feature), 🎨스타일 (Style)
