Repository codeit-sprint14-part3-4/Taskify, pull requests merged in 2025-05, with the labels that each got.

#34 [Feature/modify-dashboard-UI] 대시보드 수정 페이지 UI 구현 및 Color pin 컴포넌트화
  src/components/common/commonbutton/commonButton.module.css
  src/components/domain/colorpin/ColorPin.tsx
  src/components/domain/colorpin/colorPin.module.css
  src/components/domain/modals/dashboardCreateModal/DashboardCreateModal.tsx
  src/components/domain/modals/dashboardCreateModal/dashboardCreateModal.module.css
  src/components/domain/mydashboard/editmydashboardattribute/EditMyDashboardAttribute.tsx
  src/components/domain/mydashboard/editmydashboardattribute/editMyDashboardAttribute.module.css
  src/components/domain/mydashboard/editmydashboardinvitelog/EditMyDashboardInviteLog.tsx
  src/components/domain/mydashboard/editmydashboardinvitelog/editMyDashboardInviteLog.module.css
  src/components/domain/mydashboard/editmydashboardmember/EditMyDashboardMember.tsx
  src/components/domain/mydashboard/editmydashboardmember/editMyDashboardMember.module.css
  src/hooks/useColorPicker.ts
  src/pages/dashboard/[id]/edit.tsx
  src/pages/dashboard/[id]/edit/edit.module.css
  src/pages/dashboard/[id]/edit/index.tsx
  src/types/common/colorpin.ts
Labels: ✨기능 추가 (Feature), 🧼리팩토링 (Refactor)

#39 [Refactor/fetch-error-handling] api 전반에 fetch 예외 대응을 위한 try-catch 블록 추가
  src/api/services/authServices.ts
  src/api/services/cardsServices.ts
  src/api/services/columnsServices.ts
  src/api/services/commentsServices.ts
  src/api/services/dashboardsServices.ts
  src/api/services/invitationsServices.ts
  src/api/services/membersServices.ts
  src/api/services/usersServices.ts
Labels: 🧼리팩토링 (Refactor)

#40 [Style/modify-styles-mydashboard/edit] mydashboard 및 edit 페이지 tailwind로 마이그레이션
  src/components/common/commonbutton/commonButton.module.css
  src/components/domain/colorpin/ColorPin.tsx
  src/components/domain/mydashboard/editmydashboardinvitelog/EditMyDashboardInviteLog.tsx
  src/components/domain/mydashboard/editmydashboardinvitelog/editMyDashboardInviteLog.module.css
  src/pages/mydashboard/index.tsx
Labels: 🧼리팩토링 (Refactor), 🎨스타일 (Style)

#38 [Style/login-signup-gnb-homenavbar] 로그인, 회원가입 페이지 테일윈드로 교체 --> 코드리뷰 반영 수정본
  src/components/common/commonbutton/ButtonDashboard.module.css
  src/hooks/useDashboardInfo.ts
  src/pages/login.tsx
  src/pages/login/login.module.css
  src/pages/mypage.tsx
  src/pages/signup.tsx
  src/pages/signup/signup.module.css
Labels: 🧼리팩토링 (Refactor), 🎨스타일 (Style)

#42 [Fix/task-card-create-modal-ui]: DatePicker에서 불필요한 className 스타일 제거
  src/components/domain/modals/taskcardcreatemodal/TaskCardCreateModal.tsx
  src/components/domain/modals/taskcardeditmodal/TaskCardEditModal.tsx
Labels: 🐛버그 수정 (Bug)

#45 [feature/layout-api] 중간상태 + zustand 전역관리 + layout으로 관리
  src/components/common/badge/Badge.tsx
  src/components/common/badge/badge.module.css
  src/components/domain/modals/basemodal/FormModal.tsx
  src/components/domain/mydashboard/dashboardlist/DashboardList.tsx
  src/components/domain/mydashboard/dashboardlist/DashboardListButton.tsx
  src/components/layout/gnb/HomeNavBar.tsx
  src/components/layout/gnb/homenavbar.module.css
  src/components/layout/layout.tsx
  src/hooks/useDashboardInfo.ts
  src/pages/_app.tsx
  src/pages/dashboard/[id]/edit/index.tsx
  src/pages/dashboard/[id]/index.tsx
  src/pages/login.tsx
  src/pages/mydashboard/index.tsx
  src/pages/mypage/index.tsx
  src/stores/auth.ts
Labels: ✨기능 추가 (Feature), 🧼리팩토링 (Refactor)

#44 [Style/dropdown]: 드롭 다운 스크롤바, input 스타일 변경 및 tailwind에서 moudle.css로 변경
  src/components/dropdown/StatusDropdown.tsx
  src/components/dropdown/UserDropdown.tsx
  src/components/dropdown/statusDropdown.module.css
  src/components/dropdown/userDropdown.module.css
Labels: 🧼리팩토링 (Refactor), 🎨스타일 (Style)

#48 [chore/codereview layout] layout 코드리뷰 반영본
  src/components/layout/gnb/HomeNavBar.tsx
  src/components/layout/layout.tsx
  src/stores/auth.ts
Labels: 🧼리팩토링 (Refactor)

#43 [Feature/card-create-modal-connect] 대시보드 +버튼 클릭 시 할 일 생성 모달 연결 및 API 연결
  src/components/common/tag/Tag.tsx
  src/components/common/tag/tag.module.css
  src/components/domain/dashboard/Card.tsx
  src/components/domain/dashboard/Column.tsx
  src/components/domain/modals/taskcardcreatemodal/TaskCardCreateModal.tsx
  src/pages/dashboard/[id]/index.tsx
  src/stores/dashboardMembers.ts
  src/types/api/cards.ts
  src/types/common/tag.ts
Labels: ✨기능 추가 (Feature), 🐛버그 수정 (Bug)

#49 [Feature/invited-list] 초대받은 대시보드 API 연결
  src/components/domain/mydashboard/dashboardinvitedlist/MyInvitedDashboard.tsx
  src/pages/dashboard/[id]/index.tsx
  src/pages/login.tsx
  src/pages/mydashboard/index.tsx
Labels: ✨기능 추가 (Feature), 🐛버그 수정 (Bug), 🧼리팩토링 (Refactor)

#50 [Style/mypage]: Style - Tailwind CSS로 다시 적용
  src/pages/mypage/index.tsx
Labels: 🎨스타일 (Style)

#52 [Feature/dashboard-edit-connect] 대시보드 수정 페이지 연결 및 레이아웃 추가
  src/components/domain/dashboard/Column.tsx
  src/components/layout/gnb/HomeNavBar.tsx
  src/pages/dashboard/[id]/edit/index.tsx
Labels: ✨기능 추가 (Feature)

#57 [Feature:Modal]: 모달 삭제 기능 구현 및 컴포넌트 분리
  src/components/domain/modals/basemodal/ConfirmActionModal.tsx
  src/components/domain/modals/basemodal/DeleteActionModal.tsx
  src/components/domain/modals/basemodal/Modal.tsx
  src/pages/login.tsx
  src/pages/mypage.tsx
  src/pages/signup.tsx
  src/types/common/modal.ts
Labels: ✨기능 추가 (Feature)

#55 [Feature/editPage-member-invite-API] editPage 멤버 / 초대 API 연결
  src/components/domain/mydashboard/editmydashboardattribute/EditMyDashboardAttribute.tsx
  src/components/domain/mydashboard/editmydashboardinvitelog/EditMyDashboardInviteLog.tsx
  src/components/domain/mydashboard/editmydashboardmember/EditMyDashboardMember.tsx
  src/pages/dashboard/[id]/edit/index.tsx
Labels: ✨기능 추가 (Feature)

#58 [Feature/nav-management-button] 대시보드 권한이 있는 경우에만 관리 버튼
  src/components/layout/gnb/HomeNavBar.tsx
Labels: ✨기능 추가 (Feature)

#59 [Feature: Form모달] 모달 삭제, 생성 기능 추가
  src/components/domain/modals/basemodal/FormModal.tsx
  src/types/common/formmodal.ts
Labels: ✨기능 추가 (Feature)

#61 [Feature] 드롭다운 담당자 연결 및 카드 담당자
  src/components/domain/dashboard/Card.tsx
  src/components/domain/modals/taskcardcreatemodal/TaskCardCreateModal.tsx
  src/components/dropdown/UserDropdown.tsx
  src/components/dropdown/userDropdown.module.css
Labels: 🐛버그 수정 (Bug)

#65 [Feature/card-datail-api] 카드 상세 모달 UI 구현 및 할 일 수정 모달 연결 및 초기 데이터 세팅
  src/components/domain/dashboard/Card.tsx
  src/components/domain/dashboard/CardTable.tsx
  src/components/domain/dashboard/Column.tsx
  src/components/domain/dashboard/card.module.css
  src/components/domain/modals/taskcardeditmodal/TaskCardEditModal.tsx
  src/components/domain/modals/taskcardmodal/TaskCardModal.tsx
  src/components/domain/modals/taskcardmodal/taskCardModal.module.css
  src/components/dropdown/StatusDropdown.tsx
  src/components/dropdown/UserDropdown.tsx
  src/pages/dashboard/[id]/index.tsx
  src/stores/auth.ts
Labels: ✨기능 추가 (Feature), 🎨스타일 (Style)

#66 [Feature/homenav] HomeNavbar 프로필 이미지 추가 및 오류 수정
  src/components/layout/gnb/HomeNavBar.tsx
  src/components/layout/gnb/homenavbar.module.css
  src/pages/mypage.tsx
Labels: ✨기능 추가 (Feature), 🎨스타일 (Style)

#64 [Feature/mypage]: 마이페이지, 사이드바 스켈레톤 UI 구현 및 오류 제거
  src/components/layout/gnb/homenavbar.module.css
  src/components/layout/sidebar/Sidebar.tsx
  src/pages/mypage.tsx
Labels: ✨기능 추가 (Feature), 🎨스타일 (Style)

#63 [Feature/mydashboard-api-dropdown] 드랍다운 컴포넌트 + 마이대시보드 요구사항 만족 + api연결 --> 코드리뷰 반영 + 회원가입/로그인반응형 + 마이대시보드 페이지 테일윈드로 교체
  src/components/domain/colorpin/ColorPin.tsx
  src/components/domain/dashboard/Column.tsx
  src/components/domain/mydashboard/dashboardinvitedlist/MyInvitedDashboard.tsx
  src/components/domain/mydashboard/dashboardinvitedlist/myInvitedDashboard.module.css
  src/components/domain/mydashboard/dashboardlist/DashboardList.tsx
  src/components/domain/mydashboard/dashboardlist/DashboardListButton.tsx
  src/components/domain/mydashboard/dashboardlist/dashboardList.module.css
  src/components/domain/mydashboard/dashboardlist/dashboardListButton.module.css
  src/components/dropdown/MyDropDown.tsx
  src/components/dropdown/myDropdown.module.css
  src/pages/login.tsx
  src/pages/mydashboard.tsx
  src/pages/mydashboard/index.tsx
  src/pages/mydashboard/mydashboard.module.css
  src/pages/signup.tsx
  src/stores/auth.ts
  src/types/common/colorpin.ts
Labels: ✨기능 추가 (Feature), 🧼리팩토링 (Refactor)

#67 [Feature/column-functions] 새로운 컬럼 추가하기와 컬럼 수정 버튼 API 연동 및 기능 구현
  src/components/domain/dashboard/Column.tsx
  src/components/domain/dashboard/column.module.css
  src/pages/dashboard/[id]/index.tsx
Labels: ✨기능 추가 (Feature)

#71 [feature/login-signup-skeletone] 로그인 / 회원가입중일 때 스핀 모양으로 처리
  src/pages/login.tsx
  src/pages/signup.tsx
Labels: 🎨스타일 (Style)

#70 [Feature/editPage-requirements] editPage 요구 사항 구현 및 페이지네이션 버튼 공통 컴포넌트화
  src/components/common/commonbutton/Pagination.tsx
  src/components/common/commonbutton/pagination.module.css
  src/components/domain/modals/dashboardCreateModal/DashboardCreateModal.tsx
  src/components/domain/mydashboard/editmydashboardattribute/EditMyDashboardAttribute.tsx
  src/components/domain/mydashboard/editmydashboardattribute/editMyDashboardAttribute.module.css
  src/components/domain/mydashboard/editmydashboardinvitelog/EditMyDashboardInviteLog.tsx
  src/components/domain/mydashboard/editmydashboardinvitelog/editMyDashboardInviteLog.module.css
  src/components/domain/mydashboard/editmydashboardmember/EditMyDashboardMember.tsx
  src/components/domain/mydashboard/editmydashboardmember/editMyDashboardMember.module.css
  src/pages/dashboard/[id]/edit/edit.module.css
  src/pages/dashboard/[id]/edit/index.tsx
  src/types/common/pagination.ts
Labels: ✨기능 추가 (Feature), 🐛버그 수정 (Bug), 🎨스타일 (Style)

#73 [Style/mypage]: 마이페이지 반응형 및 스켈레톤 UI 적용, 폼 모달 수정
  src/components/domain/modals/basemodal/FormModal.tsx
  src/components/skeleton/SkeletonMyPage.tsx
  src/pages/mypage.tsx
  src/types/common/formmodal.ts
Labels: 🐛버그 수정 (Bug), 🎨스타일 (Style)

#72 [Fix/card] 전반적인 카드 관련 기능 수정 (카드 담당자, 카드 생성, 댓글 input, 댓글 UI)
  src/components/domain/dashboard/Card.tsx
  src/components/domain/dashboard/CardTable.tsx
  src/components/domain/dashboard/Column.tsx
  src/components/domain/modals/taskcardcreatemodal/TaskCardCreateModal.tsx
  src/components/domain/modals/taskcardeditmodal/TaskCardEditModal.tsx
  src/components/domain/modals/taskcardmodal/TaskCardModal.tsx
  src/components/domain/modals/taskcardmodal/taskCardModal.module.css
  src/components/layout/sidebar/sidebar.module.css
  src/pages/dashboard/[id]/index.tsx
Labels: ✨기능 추가 (Feature), 🐛버그 수정 (Bug), 🎨스타일 (Style)

#75 [Feature/card-edit-modal] 할 일 수정 모달 기능 구현(수정, input 기본값 유지, 수정 내용 반영)
  src/components/domain/dashboard/Card.tsx
  src/components/domain/dashboard/CardTable.tsx
  src/components/domain/dashboard/Column.tsx
  src/components/domain/modals/taskcardeditmodal/TaskCardEditModal.tsx
  src/components/domain/modals/taskcardmodal/TaskCardModal.tsx
  src/components/dropdown/StatusDropdown.tsx
  src/types/api/cards.ts
Labels: ✨기능 추가 (Feature), 🐛버그 수정 (Bug)

#74 [Feat/modify-editPage-requirements] 스켈레톤 UI 추가 및 CSS 수정
  src/components/common/commonbutton/pagination.module.css
  src/components/domain/mydashboard/editmydashboardattribute/EditMyDashboardAttribute.tsx
  src/components/domain/mydashboard/editmydashboardattribute/editMyDashboardAttribute.module.css
  src/components/domain/mydashboard/editmydashboardinvitelog/EditMyDashboardInviteLog.tsx
  src/components/domain/mydashboard/editmydashboardinvitelog/editMyDashboardInviteLog.module.css
  src/components/domain/mydashboard/editmydashboardmember/EditMyDashboardMember.tsx
  src/components/domain/mydashboard/editmydashboardmember/editMyDashboardMember.module.css
  src/components/skeleton/SkeletonAttribute.tsx
  src/components/skeleton/SkeletonInviteLog.tsx
  src/components/skeleton/SkeletonMember.tsx
  src/pages/dashboard/[id]/edit/index.tsx
Labels: 🧼리팩토링 (Refactor), 🎨스타일 (Style)

#77 [Style/dashboard]: dashboard 반응형 구현
  src/components/domain/dashboard/Card.tsx
  src/components/domain/dashboard/card.module.css
  src/components/domain/dashboard/column.module.css
  src/pages/dashboard/[id]/dashboard.module.css
  src/pages/dashboard/[id]/index.tsx
Labels: 🎨스타일 (Style)

#78 [Fix/task-card-modal] 날짜 오류 및 할 일 수정 담당자 placholder 변경
  src/components/domain/modals/taskcardeditmodal/TaskCardEditModal.tsx
  src/components/domain/modals/taskcardmodal/TaskCardModal.tsx
  src/components/dropdown/UserDropdown.tsx
Labels: 🐛버그 수정 (Bug)

#79 [feat/layout-card] 레이아웃 반응형
  src/components/layout/gnb/HomeNavBar.tsx
  src/components/layout/gnb/homenavbar.module.css
  src/components/layout/layout.module.css
  src/components/layout/layout.tsx
  src/components/layout/sidebar/Sidebar.tsx
  src/components/layout/sidebar/sidebar.module.css
Labels: 🎨스타일 (Style)

#80 [Fix/homenavbar-invite] HomeNavBar 수정 (초대하기 버튼, 관리 및 초대하기 유무 처리)
  src/components/layout/gnb/HomeNavBar.tsx
  src/components/layout/layout.tsx
  src/hooks/useDashboardInfo.ts
Labels: 🐛버그 수정 (Bug)

#82 [Style/mydashboard style] 마이 대시보드 페이지 스켈레톤 UI및 반응형 구현
  src/components/domain/mydashboard/dashboardinvitedlist/MyInvitedDashboard.tsx
  src/components/domain/mydashboard/dashboardinvitedlist/myInvitedDashboard.module.css
  src/components/domain/mydashboard/dashboardlist/DashboardList.tsx
  src/components/domain/mydashboard/dashboardlist/dashboardList.module.css
  src/components/domain/mydashboard/dashboardlist/dashboardListButton.module.css
  src/hooks/useIsMobile.ts
  src/pages/mydashboard.tsx
Labels: 🎨스타일 (Style)

#83 [Feature/responsive-editPage] editPage 반응형 로직 추가
  src/components/common/commonbutton/ButtonDashboard.tsx
  src/components/common/commonbutton/CommonButton.tsx
  src/components/common/commonbutton/Pagination.tsx
  src/components/common/commonbutton/pagination.module.css
  src/components/domain/mydashboard/editmydashboardattribute/EditMyDashboardAttribute.tsx
  src/components/domain/mydashboard/editmydashboardattribute/editMyDashboardAttribute.module.css
  src/components/domain/mydashboard/editmydashboardinvitelog/EditMyDashboardInviteLog.tsx
  src/components/domain/mydashboard/editmydashboardinvitelog/editMyDashboardInviteLog.module.css
  src/components/domain/mydashboard/editmydashboardmember/EditMyDashboardMember.tsx
  src/components/domain/mydashboard/editmydashboardmember/editMyDashboardMember.module.css
  src/pages/dashboard/[id]/edit/edit.module.css
  src/pages/dashboard/[id]/edit/index.tsx
Labels: 🎨스타일 (Style)

#88 [Fix/homenavbar-invite] homenavbar에서 초대하기 중복 요청 불가 처리 및 그 밖의 에러사항 수정
  src/components/layout/gnb/HomeNavBar.tsx
  src/components/layout/layout.tsx
  src/components/layout/sidebar/Sidebar.tsx
Labels: 🐛버그 수정 (Bug)

#85 [Style/taskmodal]: 모달 할 일 생성, 수정 반응형 추가
  src/components/domain/modals/taskcardcreatemodal/TaskCardCreateModal.tsx
  src/components/domain/modals/taskcardcreatemodal/taskCardCreateModal.module.css
  src/components/domain/modals/taskcardeditmodal/TaskCardEditModal.tsx
  src/components/domain/modals/taskcardeditmodal/taskCardEditModal.module.css
  src/components/dropdown/statusDropdown.module.css
  src/pages/dashboard/[id]/index.tsx
Labels: 🎨스타일 (Style)

#87 [Style/dashboard]: 대시보드 스켈레톤 UI 추가
  src/components/skeleton/SkeletonDashboard.tsx
  src/pages/dashboard/[id]/index.tsx
Labels: 🎨스타일 (Style)

#90 [Fix/homenav-button] 홈내브바 드롭다운 수정 + 대시보드 버튼 반응형 수정
  src/components/common/commonbutton/ButtonDashboard.module.css
  src/components/domain/dashboard/card.module.css
  src/components/domain/dashboard/column.module.css
  src/components/domain/mydashboard/dashboardinvitedlist/myInvitedDashboard.module.css
  src/components/domain/mydashboard/dashboardlist/DashboardListButton.tsx
  src/components/domain/mydashboard/dashboardlist/dashboardList.module.css
  src/components/domain/mydashboard/dashboardlist/dashboardListButton.module.css
  src/components/dropdown/DropdownPortal.tsx
  src/components/dropdown/MyDropDown.tsx
  src/components/dropdown/myDropdown.module.css
  src/components/layout/gnb/HomeNavBar.tsx
  src/components/layout/gnb/homenavbar.module.css
  src/pages/login.tsx
Labels: ✨기능 추가 (Feature), 🧼리팩토링 (Refactor)

#86 [Style/task card modal style] taskcardmodal 반응형 추가 및 댓글 수정기능 디자인 변경 및 댓글 무한 스크롤 기능 구현
  src/components/domain/modals/taskcardmodal/TaskCardModal.tsx
  src/components/domain/modals/taskcardmodal/taskCardModal.module.css
  src/pages/mydashboard.tsx
Labels: ✨기능 추가 (Feature)

#91 [Feature/task-detail-modal-infinite-scroll] 할 일 카드 상세 모달 댓글 무한 스크롤 로직 추가
  src/components/domain/modals/taskcardmodal/TaskCardModal.tsx
  src/components/domain/modals/taskcardmodal/taskCardModal.module.css
Labels: ✨기능 추가 (Feature)

#92 [Fix/calendar] 날짜 캘린더 1970.01.01 뜨는 오류 재수정
  src/components/domain/modals/taskcardmodal/TaskCardModal.tsx
Labels: 🐛버그 수정 (Bug)

#93 [feat/card-limit2] - 카드 무한스크롤
  src/components/domain/dashboard/Column.tsx
  src/components/layout/sidebar/Sidebar.tsx
  src/components/layout/sidebar/sidebar.module.css
Labels: ✨기능 추가 (Feature)

#94 [Fix/error] 전체적인 에러 고침 --> 피드백 반영 + 전체적인 오류 고침
  src/components/domain/modals/dashboardCreateModal/DashboardCreateModal.tsx
  src/components/domain/modals/taskcardmodal/TaskCardModal.tsx
  src/components/domain/mydashboard/editmydashboardattribute/EditMyDashboardAttribute.tsx
  src/components/domain/mydashboard/editmydashboardinvitelog/EditMyDashboardInviteLog.tsx
  src/components/domain/mydashboard/editmydashboardmember/EditMyDashboardMember.tsx
  src/components/layout/layout.tsx
  src/components/layout/sidebar/Sidebar.tsx
  src/pages/dashboard/[id]/edit/index.tsx
  src/pages/dashboard/[id]/index.tsx
  src/pages/mydashboard.tsx
  src/pages/mypage.tsx
  src/pages/signup.tsx
Labels: 🐛버그 수정 (Bug), 🧼리팩토링 (Refactor)

#95 [feat/lightningcss] 라이브러리설치
  package-lock.json
  package.json
  src/components/common/animatedmodalcontainer/AnimatedModalContainer.tsx
  src/components/common/badge/Badge.tsx
  src/components/common/commonbutton/buttonDashboard.module.css
  src/components/common/tag/Tag.tsx
  src/components/domain/colorpin/ColorPin.tsx
  src/components/domain/modals/taskcardcreatemodal/TaskCardCreateModal.tsx
  src/components/domain/modals/taskcardeditmodal/TaskCardEditModal.tsx
  src/components/domain/modals/taskcardmodal/TaskCardModal.tsx
  src/components/layout/sidebar/sidebar.module.css
  src/pages/mypage.tsx
Labels: ✨기능 추가 (Feature), 🧼리팩토링 (Refactor)

#96 [Feature/drag-n-drop] 카드 드래그앤드롭 구현
  next.config.js
  package-lock.json
  package.json
  src/components/domain/dashboard/Card.tsx
  src/components/domain/dashboard/CardTable.tsx
  src/components/domain/dashboard/Column.tsx
  src/pages/dashboard/[id]/index.tsx
Labels: ✨기능 추가 (Feature)

#98 README 수정
  README.md
Labels: 📄문서 (Docs)

#97 [Feature/sidebar]: 사이드바 스타일 및 페이지네이션 변경
  public/assets/image/arrow-left-bold.svg
  public/assets/image/arrow-right-bold.svg
  src/components/common/commonbutton/Pagination.tsx
  src/components/common/commonbutton/pagination.module.css
  src/components/domain/mydashboard/editmydashboardinvitelog/EditMyDashboardInviteLog.tsx
  src/components/domain/mydashboard/editmydashboardmember/EditMyDashboardMember.tsx
  src/components/layout/sidebar/Sidebar.tsx
  src/components/layout/sidebar/sidebar.module.css
Labels: ✨기능 추가 (Feature), 🎨스타일 (Style)

#100 [Style] console.log 제거 및 homeNavbar 수정
  src/components/domain/dashboard/Column.tsx
  src/components/layout/gnb/HomeNavBar.tsx
Labels: 🔥긴급 수정 (Hotfix)

#101 [Fix/card-infinite] 카드 무한 스크롤 (최신순 제외) + 댓글 프로필 이미지 width 설정
  src/components/domain/dashboard/CardTable.tsx
  src/components/domain/dashboard/Column.tsx
  src/components/domain/dashboard/column.module.css
  src/components/domain/modals/taskcardmodal/TaskCardModal.tsx
  src/components/domain/modals/taskcardmodal/taskCardModal.module.css
Labels: 🐛버그 수정 (Bug)

#103 [feat/mydashboard-list-button] 대시보드 목록 수정
  src/components/domain/mydashboard/dashboardlist/DashboardList.tsx
  src/components/domain/mydashboard/dashboardlist/dashboardList.module.css
  src/pages/mydashboard.tsx
Labels: 🐛버그 수정 (Bug), 🧼리팩토링 (Refactor)

#104 [Task] 카드 댓글 엔터, 파일명, 초대 비활성화 버튼, 메인페이지 스크롤 제거
  src/components/domain/modals/taskcardcreatemodal/TaskCardCreateModal.tsx
  src/components/domain/modals/taskcardcreatemodal/taskCardCreateModal.module.css
  src/components/domain/modals/taskcardeditmodal/TaskCardEditModal.tsx
  src/components/domain/modals/taskcardeditmodal/taskCardEditModal.module.css
  src/components/domain/modals/taskcardmodal/TaskCardModal.tsx
  src/components/domain/modals/taskcardmodal/taskCardModal.module.css
  src/components/layout/layout.tsx
  src/pages/dashboard/[id]/edit/index.tsx
  src/pages/dashboard/[id]/index.tsx
  src/pages/mydashboard.tsx
  src/pages/mypage.tsx
Labels: 🐛버그 수정 (Bug), 🎨스타일 (Style)

#105 [Feat/mobile] 모바일 전체적으로 css 수정
  src/components/common/commonbutton/buttonDashboard.module.css
  src/components/domain/dashboard/column.module.css
  src/components/domain/modals/taskcardcreatemodal/taskCardCreateModal.module.css
  src/components/domain/mydashboard/dashboardlist/DashboardList.tsx
  src/components/domain/mydashboard/dashboardlist/dashboardList.module.css
  src/components/domain/mydashboard/dashboardlist/dashboardListButton.module.css
  src/components/domain/mydashboard/editmydashboardattribute/editMyDashboardAttribute.module.css
  src/components/domain/mydashboard/editmydashboardinvitelog/editMyDashboardInviteLog.module.css
  src/components/domain/mydashboard/editmydashboardmember/editMyDashboardMember.module.css
  src/components/layout/gnb/HomeNavBar.tsx
  src/components/layout/gnb/homenavbar.module.css
  src/components/layout/layout.module.css
  src/components/layout/sidebar/sidebar.module.css
  src/pages/dashboard/[id]/dashboard.module.css
  src/pages/dashboard/[id]/edit/edit.module.css
  src/pages/dashboard/[id]/edit/index.tsx
  src/pages/dashboard/[id]/index.tsx
  src/pages/login.tsx
  src/pages/mydashboard.tsx
  src/pages/mypage.tsx
  src/pages/signup.tsx
Labels: 🎨스타일 (Style)

#106 [Fix] 에러사항 코드 수정
  src/components/common/badge/Badge.tsx
  src/components/common/tag/Tag.tsx
  src/components/domain/dashboard/Card.tsx
  src/components/domain/dashboard/Column.tsx
  src/components/domain/dashboard/column.module.css
  src/components/domain/modals/taskcardcreatemodal/TaskCardCreateModal.tsx
  src/components/domain/modals/taskcardeditmodal/TaskCardEditModal.tsx
  src/components/domain/modals/taskcardmodal/taskCardModal.module.css
  src/components/domain/mydashboard/dashboardlist/DashboardList.tsx
  src/components/domain/mydashboard/dashboardlist/dashboardList.module.css
Labels: 🐛버그 수정 (Bug), 🎨스타일 (Style)

#107 [Feature/toast] - alert 로직 toast로 변경
  package-lock.json
  package.json
  src/components/domain/modals/dashboardCreateModal/DashboardCreateModal.tsx
  src/components/domain/mydashboard/editmydashboardattribute/EditMyDashboardAttribute.tsx
  src/components/domain/mydashboard/editmydashboardinvitelog/EditMyDashboardInviteLog.tsx
  src/components/domain/mydashboard/editmydashboardmember/EditMyDashboardMember.tsx
  src/components/toast/Toast.tsx
  src/components/toast/toast.module.css
  src/context/ToastContext.tsx
  src/pages/_app.tsx
  src/pages/dashboard/[id]/edit/index.tsx
  src/pages/dashboard/[id]/index.tsx
  src/pages/login.tsx
  src/pages/signup.tsx
Labels: ✨기능 추가 (Feature)

#108 [Style/Tag]: 태그 색상 유지
  src/components/common/badge/Badge.tsx
  src/components/domain/dashboard/Card.tsx
  src/components/domain/dashboard/column.module.css
  src/components/domain/modals/taskcardcreatemodal/TaskCardCreateModal.tsx
  src/components/domain/modals/taskcardeditmodal/TaskCardEditModal.tsx
  src/components/domain/modals/taskcardmodal/TaskCardModal.tsx
  src/components/domain/modals/taskcardmodal/taskCardModal.module.css
Labels: ✨기능 추가 (Feature), 🐛버그 수정 (Bug)

#110 [Style:card] 카드 모달, Column Title 수정
  package-lock.json
  src/components/domain/dashboard/column.module.css
  src/components/domain/modals/taskcardmodal/taskCardModal.module.css
Labels: 🎨스타일 (Style)

#112 [Refactor/modify-mydashboard-style] mydashboard style 수정
  src/components/domain/mydashboard/dashboardlist/dashboardList.module.css
  src/components/domain/mydashboard/dashboardlist/dashboardListButton.module.css
  src/pages/mydashboard.tsx
Labels: 🧼리팩토링 (Refactor), 🎨스타일 (Style)

#111 [style/modal-mobile] 모바일 모달 수정
  src/components/domain/modals/basemodal/baseModal.module.css
  src/components/domain/modals/taskcardcreatemodal/taskCardCreateModal.module.css
  src/components/domain/modals/taskcardeditmodal/taskCardEditModal.module.css
  src/components/domain/mydashboard/dashboardinvitedlist/myInvitedDashboard.module.css
  src/components/domain/mydashboard/dashboardlist/DashboardList.tsx
  src/components/domain/mydashboard/dashboardlist/dashboardList.module.css
  src/components/layout/gnb/HomeNavBar.tsx
  src/components/layout/gnb/homenavbar.module.css
  src/components/layout/layout.module.css
  src/pages/mypage.tsx
Labels: 🎨스타일 (Style)

#114 [feat/comment-bug]댓글수정
  src/components/domain/modals/taskcardmodal/TaskCardModal.tsx
  src/components/domain/modals/taskcardmodal/taskCardModal.module.css
  src/components/layout/layout.module.css
Labels: 🧼리팩토링 (Refactor), 🎨스타일 (Style)

#115 [Fix/card-modal-sticky] PC 가로 스크롤바 수정
  src/components/domain/dashboard/column.module.css
  src/pages/_app.tsx
  src/pages/dashboard/[id]/dashboard.module.css
  src/styles/globals.css
Labels: 🧼리팩토링 (Refactor), 🎨스타일 (Style)
